### ISSUE TITLE
Navbar & Menu Hijacking

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/netbeans-plugin#28]
I don't think it is a good idea to have the CI stuff as the first entry in a menu (File, Tools), or in the toolbar. This feels presumptuous. They should be located more appropriately, and consistent with other framework plugins.

**Comment by djwoods** [comment]
I've moved the search bar. It's now in "Toolbars/CodeIgniter".
@madmax330, can you move the code generator button into the same toolbar folder and close this issue?
