### ISSUE TITLE
Plugin integration

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/netbeans-plugin#29]
Tools/Plugins shows our plugin, but with the name "netbeans plugin" and in the category "uncategorized". These should be "CodeIgniter3 framework" and "PHP", respectively.

**Comment by djwoods** [comment]
This might be something that we set when we submit the plugin to the NetBeans portal.
I can't seem to find anywhere in the Yii plugin that sets the name, yet it shows up as "PHP Yii Framework" and category "PHP"
