### ISSUE TITLE
Plugin manager - version detection

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/netbeans-plugin#31]
If I select the folder that holds the CI framework, eg. /pub7/htdocs/system3, it shows in the plugin config window afterwards as "/pub7/htdocs". The subfolder with the framework has been dropped.

When I click the update button to try to fix the selection, the starting folder is inside my NB-plugin project?? I would have though that the current system folder location would be the starting point, or even the project I have open, not the plugin one?

How is the CI version set? Its placement beside the update button suggests that it would be detected on "update", or selectable on update? Or is this provision for selecting between different versions of CI installed on the user's machine?

**Comment by ahnh** [comment]
CI version is not supported yet, it is more about the placeholder. I can extract the version from "CodeIgniter.php", if it's going to be remained same in CI 3.0.

**Comment by jim-parry** [comment]
ps If a PR fixes an issue, reference it as fixes#31 and not just #31, and the issue should then be closed automatically :)

Not sure if the comment has to be in the "subject" line of the PR or not :-/
