### ISSUE TITLE
Personal starter project?

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/netbeans-plugin#34]
As a CI developer, I build my own "normal" starter project, with the pre-built classes I always use and my favorite plugins. As a plugin user, how do I add that to the list of available starter projects?

**Comment by djwoods** [comment]
Can you not just create a "PHP application from existing sources" and point it at the root source folder of your "normal" starter project?

To me, that seems slightly easier than first going through a wizard to add your "normal" starter project to the list of starter projects, and then going through the New Project wizard and choosing it from a list there. What do you think @jim-parry ?

**Comment by djwoods** [comment]
http://bits.netbeans.org/8.0/javadoc/org-netbeans-modules-projectuiapi/org/netbeans/spi/project/ui/templates/support/package-summary.html

This package would seem to allow us to implement the feature, however

**Comment by DevotionGeo** [comment]
Though its off topic, but you people better look at this plugin also at https://github.com/nbphpcouncil/nb-ci-plugin

**Comment by jim-parry** [comment]
I have flagged the project as not completed, but am leaving the repository up in case anyone finds it helpful.
