### ISSUE TITLE
Sample starters

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/netbeans-plugin#35]
I see three "typical" starter projects in the list of PHP samples: TodoList (no framework), Rent a Flat (Symfony & Zend), and Calculator (for PHPUnit, Atoum and Nette).

I can make CodeIgniter equivalents for these, but what do I then do with those?

**Comment by djwoods** [comment]
@jim-parry Please post the CodeIgnter equivalents on the Trello board once you've completed them, and I'll bundle them in to the plugin
