### ISSUE TITLE
Readme needs to be updated

### ISSUE THREAD

**Issue by zhanghongyi** [bcit-ci/netbeans-plugin#69]
The current readme page seems to be just a copy-paste of CodeIgniter's readme page. It does not explain what it does as well as the usages. Maybe we can simply move some things out of the user guides to make the readme more specifically?

**Comment by TamakiSakura** [comment]
Maybe we could add link in readme to the guide folder?

**Comment by jim-parry** [comment]
I have flagged the project as not completed, but am leaving the repository up in case anyone finds it helpful.
